### ISSUE TITLE
sumo-sources.json.tmpl Templatizer Removes Last Brace

### ISSUE THREAD

**Issue by hannahsquier** [SumoLogic/sumologic-collector-docker#44] opened 2017-04-18 21:35 UTC
I have the following `sumo-sources.json.tmpl` file:
```
{
  "api.version": "v1",
  "sources": [
    { 
      "sourceType": "Syslog",
      "name": "${ENVIRONMENT}-name",
      "port": ${SUMO_PORT},
      "protocol": "TCP",
      "encoding": "UTF-8",
      "forceTimeZone": false,
      "category": "${ENVIRONMENT}/category"
    }
]
}
```
When I run my docker file, I get `Could not read file: /opt/SumoCollector/sumo-sources.json: Unexpected end-of-input: expected close marker for OBJECT (from [Source: /opt/SumoCollector/sumo-sources.json; line: 2, column: 0])
jvm 1    |  at [Source: /opt/SumoCollector/sumo-sources.json; line: 16, column: 284]`

After further investigation, I realized that when the template is converted to json, the closing brace is getting removed. When I add an extra brace (invalidating the json) it successfully creates the sumo source.

**Comment by maimaisie** [comment] 2017-05-01 19:44
@hannahsquier Thanks for finding this bug! We will investigate and provide a fix.

**Comment by maimaisie** [comment] 2017-05-23 18:48
Hi @hannahsquier, I tried to reproduce with the template file you provided, and I can create the source successfully without having to add extra brace. Here is the `sumo-sources.json` that got created when I use your template file, and supplying `ENVIRONMENT=prod`, `SUMO_PORT=1004`
```
{
  "api.version": "v1",
  "sources": [
    {
      "sourceType": "Syslog",
      "name": "prod-name",
      "port": 1004,
      "protocol": "TCP",
      "encoding": "UTF-8",
      "forceTimeZone": false,
      "category": "prod/category"
    }
]
}
```

**Comment by maimaisie** [comment] 2017-06-12 18:51
Closing the issue as cannot reproduce

**Closed by maimaisie** 2017-06-12 18:51 UTC
